export const Data = [
  {
    name: "Moa",
    translate: true,
    isTranslate: false,
    before1: "meow meowww ",
    before2: "mewww mewooow ",
    before3: "miaww mewooooww!!",
    after1: "hii...",
    after2: "demi sebungkus whiskas ",
    after3: "hbd nak divaa!!",
    image: "/odut.jpg",
  },
  {
    name: "Boneng",
    translate: true,
    isTranslate: false,
    before1: "miawww.... ",
    before2: "miaww...",
    before3: "miaw?",
    after1: "ka divaa... ",
    after2: "selamat hari lahir",
    after3: "jadi babunya boneng ya?",
    image: "/boneng.jpg",
  },
  {
    name: "Wiwi",
    translate: true,
    isTranslate: false,
    before1: "miaww...",
    before2: "meowww",
    before3: "meoww mewooow",
    after1: " halo mbaa",
    after2: "jadi babu yang lebih baik lagi ya",
    after3: "selamat bertambah tua",
    image: "/wiwi.jpg",
  },
  {
    name: "Diva",
    translate: false,
    before: "",
    after:
      "hiiii kamu, tahun ini sungguh baik rasanya, tetap baik ditahun-tahun selanjutnya. dan selamat ulang tahun",
    image: "/divagede.jpg",
  },
  {
    name: "Diva Kecil",
    translate: false,
    before: "",
    after:
      "kakk, gakerasa kita udah bertambah tua, tetap lucukan seperti dulu? selamat merayakan hari jadi kita",
    image: "/divakecil.jpg",
  },
];
